### ISSUE TITLE
Add please html5lib to requirements.txt

### ISSUE THREAD

**Issue by cipher387** [h3x0crypt/FindMyAss#1]
Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?
Traceback (most recent call last):
  File "FindMyAss.py", line 287, in <module>
    main()
  File "FindMyAss.py", line 265, in main
    domain, data = fetchDomainData(domain)
TypeError: cannot unpack non-iterable NoneType object

**Comment by h3x0crypt** [comment]
html5lib module added to requirements
thank you
