### ISSUE TITLE
Errors on some domains

### ISSUE THREAD

**Issue by 5ton3** [h3x0crypt/FindMyAss#2]
Some domains produce following error  (eg gov.uk)
list index out of range
Traceback (most recent call last):
  File "FindMyAss.py", line 287, in <module>
    main()
  File "FindMyAss.py", line 267, in main
    print(f"\n        {bcolors.HEADER}      <INFO> DOMAIN     :  {bcolors.ENDC}{bcolors.BOLD}{data['domain']}{bcolors.ENDC}")
TypeError: 'NoneType' object is not subscriptable

**Comment by h3x0crypt** [comment]
thank you for reporting this issue
i'm working on new version of HostSpider and i will fix many issues
stay tuned 
best regards
